export enum Permissions {
  CanReadProject = 1,
  CanEditProject,
  CanCloseProject,
  CanCreateProjectRole,
  CanEditProjectTeam,
  CanCreateTask,
  CanEditTask,
  CanEditTaskStatus,
  CanCreateSprint,
  CanStartSprint,
  CanFinishSprint,
  CanStartDaily,
  CanStartScrumPocker,
  CanSetTaskPoints,
  CanResetScrumPocker,
  CanStartDemo,
  CanCreateDemoNotes,
  CanStartRetro,
  CanCreateRetroActions,
  CanCreateEpics,
}
